### ISSUE TITLE
Falling Whilst Standing on Corners

### ISSUE THREAD

**Issue by pebleblebl** [Gronkins/Bullet_Bunny#6]
## Version: 2023-05-01
**Description:**
Buck enters the free-fall state even though he is grounded. This occurs when he is standing on the rounded corners of a platform.
***
**Reproducing the bug + theory:**

Stand on the very edge of a platform.

The collision boxes of the platforms seemed to be directly linked to their sprites rather than going off of a rectangular collision box with sharp corners. Buck has a collision box that checks whether he is grounded or not. When he stands on the edge of the platforms, the grounded checkbox doesn’t connect with the platform’s collision box due to the rounded edges.
***
**Potential Solution / Solution:**

Fix the collision boxes of the platform so that the rounded edges are purely visual and the collision box works like a regular rectangle. The corners of this rectangle should go slightly over the visual boundaries of the tile.
***
**Operating System:**

Windows 10

**Comment by Gronkins** [comment]
The issue was resolved by adjusting Buck's collision hitbox, Buck's collision hitbox has been centred to avoid inconsistencies when standing on the corners of platforms.
